### ISSUE TITLE
Review step#2. No quite completed

### ISSUE THREAD

**Issue by jgtres** [jworozco/tarea_regex#1]
Hi, here is the step#2 description

2. Eliminar el espacio en blanco en el nombre de la celda (NNG45Y00)

and here what your code is generating, please double check.

"GateNG45Y 67 at 2024\06\11 17:59:00,GateNG45Y 68 at 2024\06\11 18:09:00,..."

**Comment by jworozco** [comment]
ah ok si, ya veo, es el espacio despues no antes... voy...

**Comment by jworozco** [comment]
listo, creo que ya.
